name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC, see https://docs.npmjs.com/trusted-publishers
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - run: npm ci
      - name: Set package version from release tag
        run: npm version "${RELEASE_TAG#v}" --no-git-tag-version
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
